### ISSUE TITLE
Question SPI

### ISSUE THREAD

**Issue by paula75** [fngstudios/ADE7758#1]
Hi!

First of all thank you very much for your code, it is very helpful.
I have a question about the example in Arduino, i don't know why you implement the function closeSPI (that change the mode 2 to 0), and the in the loop you change it back to mode 2 with the function setSPI

**Comment by fngstudios** [comment]
Hi, Im glad you find it usefull.
The thing with that code is that the library was developed with a specific application in mind wich also has another spi slaves. The other SPI slaves use MODE0 and thats why I used those functions, one to change the MODE to 2 and the another to change it back to 0. In the example the ADE is the only SPI slave and you can simply change the MODE to 2 once and delete any other setSPI instances.

**Comment by paula75** [comment]
Ok, perfect.
Thanks!

**Comment by CiochinaVitalie** [comment]
Hi!
I examined the code, I noticed that there are some errors in the functions getAVRMS (), getBVRMS (), and getCVRMS () ----you lost t_of = 1 into 
if ((millis() - lastupdate) > 20) 
		{ 
			break;  
		}
Thanks!

**Comment by fngstudios** [comment]
Thank you! I'll update it soon.
