### ISSUE TITLE
Current Measure

### ISSUE THREAD

**Issue by paula75** [fngstudios/ADE7758#2]
Hi again,

I am trying to measure the current with a split core, but the value of Current_x in all phases is zero. I connected the same pin of IAP to VAP to see if the error is on the circuit, in the configuration of the device or in the code. If i connect the same entrance in IAP and VAP just VAP show a valid number. 
Have you measured the current before with the code or you think that there may be a problem in the connection?

Thanks for your answer!

**Comment by fngstudios** [comment]
It is working fine in my setup, maybe some wrong connection or configuration. Post the schematic and code.
