### ISSUE TITLE
Reading the Waveform from ADE7758 using STM32F746 Discovery Board in Arduino IDE

### ISSUE THREAD

**Issue by mrajaraghavan** [fngstudios/ADE7758#4]
Hi, Have you tried reading the waveform of any channel. I'm trying to interface ADE7758 with STM32f746 Discovery board in Arduino IDE. I'm able to set the interrupt Mask Registers but not getting the ISR Interrupt continuously. Can you help me in this regard.

Thanks

**Comment by fngstudios** [comment]
Yes I did, but with an ESP32. We had to rewrite SPI libs to work outside RTOS locks and DMA. This device needs very short but very frequent ISR calls and as soon as you mix that with any type of MUTEX you get in trouble. I don't know how your HW looks like but I've seen people forgeting the pull-up resistor in the interrupt pin.

Sorry for the really late response, I've stopped using Github for a long time and now I am using it again.
